CREATE SEQUENCE coffee_id_seq
  START WITH 101
  INCREMENT BY 1
  MINVALUE 101;

create table tbl_coffee
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
    code        text not null unique,
    name        text not null,
    description text,
    image_url   text,
    price       NUMERIC(5, 2) not null
);

CREATE INDEX coffee_id_idx ON tbl_coffee (id);